import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { dateStamp } from "./capture-plan.ts";
import { groupEndpoints, renderEndpointsMarkdown, type Endpoint } from "./interactions-model.ts";
import type { NetworkEvent } from "./network-log.ts";
import { OUT_DIR, RECON_ROOT } from "./config.ts";

/**
 * STORY_004: reduces every raw network log of the day (recon/out/<date>/*.jsonl)
 * into docs/recon/<date>/endpoints.json and endpoints.md — one row per
 * method + host + path, with counts, statuses, cadence and a redacted response
 * shape. The narrative (interactions.md) is written by hand from this.
 * Runs offline: no browser, no network.
 */

const stamp = process.argv[2] ?? dateStamp(new Date());
const rawDir = path.join(OUT_DIR, stamp);
const docsDir = path.join(RECON_ROOT, "..", "docs", "recon", stamp);

if (!existsSync(rawDir)) {
  console.error(`no raw log directory at recon/out/${stamp}`);
  process.exit(1);
}

const files = readdirSync(rawDir).filter((f) => f.endsWith(".jsonl")).sort();
const perFile: { file: string; endpoints: Endpoint[] }[] = [];
const all: NetworkEvent[] = [];
for (const file of files) {
  const events = readFileSync(path.join(rawDir, file), "utf8")
    .split("\n")
    .filter((line) => line.trim())
    .map((line) => JSON.parse(line) as NetworkEvent);
  all.push(...events);
  perFile.push({ file, endpoints: groupEndpoints(events) });
}
const combined = groupEndpoints(all);

mkdirSync(docsDir, { recursive: true });
writeFileSync(path.join(docsDir, "endpoints.json"), `${JSON.stringify({ date: stamp, files, combined, perFile }, null, 2)}\n`);

const md: string[] = [];
md.push(`# Endpoints observed — agent.minimax.io — ${stamp}`, "");
md.push(`Reduced from ${files.length} raw log(s) (${all.length} events) in the gitignored \`recon/out/${stamp}/\`. Paths carry placeholders for ids; no query strings; response shapes show keys and types only. Generated by \`pnpm recon:interactions\`; the narrative is in [interactions.md](interactions.md).`, "");
md.push("## All logs combined", "", renderEndpointsMarkdown(combined), "");
for (const { file, endpoints } of perFile) {
  md.push(`## ${file}`, "", renderEndpointsMarkdown(endpoints), "");
}
md.push("## Response shapes (first JSON body seen per endpoint, combined)", "");
for (const e of combined) {
  if (e.responseShape === undefined) continue;
  md.push(`### ${e.method} ${e.host}\`${e.path}\``, "", "```json", JSON.stringify(e.responseShape, null, 1), "```", "");
}
writeFileSync(path.join(docsDir, "endpoints.md"), md.join("\n"));
console.log(`Wrote docs/recon/${stamp}/endpoints.{json,md}: ${combined.length} endpoints from ${files.length} log(s), ${all.length} events.`);
