"use client";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { ASSET_CHIPS, ASSET_TABS, fileNameFor, filterAssets, type AssetChip } from "@/lib/assets-filter";
import { cx } from "@/lib/cx";
import type { HistoryEntry } from "@/lib/history-store";
import styles from "./assets.module.css";

const INERT_TITLE = "Not part of MiniMax Local";

export interface AssetsPageProps {
  readonly fetchImpl?: typeof fetch;
  /** Injected for tests; the page confirms with window.confirm. */
  readonly confirmImpl?: (message: string) => boolean;
}

/** Assets (STORY_015): every finished video as a tile, a preview modal, download, open task, delete from history. */
export function AssetsPage({ fetchImpl, confirmImpl }: AssetsPageProps) {
  const doFetch = fetchImpl ?? fetch;
  const confirmDelete = confirmImpl ?? ((message: string) => window.confirm(message));
  const [entries, setEntries] = useState<readonly HistoryEntry[] | undefined>(undefined);
  const [chip, setChip] = useState<AssetChip>("All");
  const [query, setQuery] = useState("");
  const [menuFor, setMenuFor] = useState<string | undefined>(undefined);
  const [previewId, setPreviewId] = useState<string | undefined>(undefined);
  const dialog = useRef<HTMLDialogElement>(null);
  const lastTile = useRef<HTMLElement | null>(null);

  const fetchEntries = (): Promise<readonly HistoryEntry[]> =>
    doFetch("/api/history")
      .then(async (res) => ((await res.json()) as { entries: HistoryEntry[] }).entries)
      .catch(() => []);
  const load = (): Promise<void> => fetchEntries().then(setEntries);
  useEffect(() => {
    let cancelled = false;
    fetchEntries()
      .then((list) => {
        if (!cancelled) setEntries(list);
      })
      .catch(() => undefined);
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps -- once on mount
  }, []);

  useEffect(() => {
    if (!menuFor) return;
    const close = (event: MouseEvent): void => {
      if (!(event.target instanceof Element) || !event.target.closest("[data-kebab]")) setMenuFor(undefined);
    };
    window.addEventListener("mousedown", close);
    return () => {
      window.removeEventListener("mousedown", close);
    };
  }, [menuFor]);

  const preview = entries?.find((e) => e.id === previewId);
  useEffect(() => {
    const el = dialog.current;
    if (!el) return;
    if (preview && !el.open) el.showModal();
    if (!preview && el.open) el.close();
  }, [preview]);

  const openPreview = (id: string, from: HTMLElement): void => {
    lastTile.current = from;
    setPreviewId(id);
  };
  const closePreview = (): void => {
    setPreviewId(undefined);
    lastTile.current?.focus();
  };
  const remove = async (entry: HistoryEntry): Promise<void> => {
    setMenuFor(undefined);
    if (!confirmDelete(`Delete "${entry.title}" from history? The file on the Spark is untouched.`)) return;
    await doFetch(`/api/history/${encodeURIComponent(entry.id)}`, { method: "DELETE" });
    await load();
  };

  const shown = entries ? filterAssets(entries, { chip, query }) : [];
  const kind = chip === "All" ? "assets" : chip.toLowerCase();

  return (
    <main className={styles.page}>
      <h1 className={styles.title}>Assets</h1>
      <div className={styles.tabs} role="tablist">
        {ASSET_TABS.map((tab, i) => (
          <button key={tab} type="button" role="tab" aria-selected={i === 0} aria-disabled={i === 0 ? undefined : "true"} title={i === 0 ? undefined : INERT_TITLE} className={cx(styles.tab, i === 0 && styles.tabActive)}>
            {tab}
          </button>
        ))}
      </div>
      <div className={styles.toolbar}>
        {ASSET_CHIPS.map((c) => (
          <button key={c} type="button" className={cx(styles.chip, chip === c && styles.chipActive)} aria-pressed={chip === c} onClick={() => { setChip(c); }}>
            {c}
          </button>
        ))}
        <label className={styles.search}>
          <span aria-hidden="true">🔍</span>
          <input type="search" placeholder="Search by file or task name" aria-label="Search by file or task name" value={query} onChange={(event) => { setQuery(event.target.value); }} />
        </label>
      </div>

      {entries !== undefined && shown.length === 0 ? (
        <div className={styles.empty} data-testid="assets-empty">
          <p className={styles.emptyTitle}>{chip === "All" && query === "" ? "No assets yet" : `No ${kind} yet`}</p>
          <p className={styles.emptyText}>Files generated by AI and uploaded by you will appear here</p>
          <Link href="/" className={styles.primary}>+ New task</Link>
        </div>
      ) : (
        <div className={styles.grid}>
          {shown.map((entry) => {
            const name = fileNameFor(entry);
            const resultPath = `/api/jobs/${encodeURIComponent(entry.id)}/result`;
            return (
              <article key={entry.id} className={styles.tile} data-testid="asset-tile" aria-label={name}>
                <div className={styles.poster}>
                  {/* eslint-disable-next-line @next/next/no-img-element -- the adapter's first frame, served by our route */}
                  <img src={`/api/jobs/${encodeURIComponent(entry.id)}/poster`} alt="" onError={(event) => { event.currentTarget.style.display = "none"; }} />
                  <button type="button" className={styles.preview} aria-label={`Preview ${name}`} onClick={(event) => { openPreview(entry.id, event.currentTarget); }}>▶ Preview</button>
                </div>
                <div className={styles.name}>
                  <span aria-hidden="true">▣</span>
                  <span className={styles.nameText}>{name}</span>
                  <span className={styles.kebabWrap} data-kebab={entry.id}>
                    <button type="button" className={styles.kebab} aria-label={`More actions for ${name}`} aria-haspopup="menu" aria-expanded={menuFor === entry.id} onClick={() => { setMenuFor(menuFor === entry.id ? undefined : entry.id); }}>⋯</button>
                    {menuFor === entry.id ? (
                      <div className={styles.menu} role="menu" aria-label={`Actions for ${name}`}>
                        <Link href={`/task/${encodeURIComponent(entry.id)}`} role="menuitem" className={styles.menuItem}>Open task</Link>
                        <Link href={`/task/${encodeURIComponent(entry.id)}?extend`} role="menuitem" className={styles.menuItem}>Extend</Link>
                        <a href={`${resultPath}?download`} download={name} role="menuitem" className={styles.menuItem}>Download</a>
                        <button type="button" role="menuitem" className={cx(styles.menuItem, styles.menuDanger)} onClick={() => void remove(entry)}>Delete from history</button>
                      </div>
                    ) : null}
                  </span>
                </div>
              </article>
            );
          })}
        </div>
      )}

      <dialog ref={dialog} className={styles.dialog} aria-label={preview ? fileNameFor(preview) : "Preview"} onClose={closePreview} onClick={(event) => { if (event.target === dialog.current) closePreview(); }}>
        {preview ? (
          <>
            <div className={styles.dialogHead}>
              <span className={styles.dialogTitle}>{fileNameFor(preview)}</span>
              <a className={styles.dialogButton} href={`/api/jobs/${encodeURIComponent(preview.id)}/result?download`} download={fileNameFor(preview)} aria-label="Download" title="Download">⤓</a>
              <Link className={styles.dialogButton} href={`/task/${encodeURIComponent(preview.id)}`} aria-label="Open task" title="Open task">↗</Link>
              <button type="button" className={styles.dialogButton} aria-label="Close" onClick={closePreview}>×</button>
            </div>
            <video className={styles.dialogVideo} controls playsInline preload="metadata" poster={`/api/jobs/${encodeURIComponent(preview.id)}/poster`} src={`/api/jobs/${encodeURIComponent(preview.id)}/result`} data-testid="preview-video">
              <track kind="captions" />
            </video>
          </>
        ) : null}
      </dialog>
    </main>
  );
}
